---
- hosts: all
  tasks:
    - name: Fetch Ray logs
      ansible.posix.synchronize:
        src: /tmp/ray/session_latest/logs
        dest: /tmp/ray/session_latest/{{ inventory_hostname }}
        mode: pull
