---
- namee: Setup Azure
  hosts: all
  vars:
    data_disk: /dev/disk/azure/scsi1/lun0
    ssd_device: /dev/disk/azure/scsi1/lun0-part1
    mnt_path: /mnt/data0
    workdir: ~/raysort
    pythondir: ~/miniconda3/envs/raysort/bin
  tasks:
    - name: Create a new ext4 partition
      become: true
      community.general.parted:
        device: "{{ data_disk }}"
        number: 1
        state: present
        label: gpt
        name: data0
        fs_type: ext4

    - name: Create filesystem on nvme
      become: true
      community.general.filesystem:
        fstype: ext4
        dev: "{{ ssd_device }}"

    - name: Create mount directory
      become: true
      ansible.builtin.file:
        path: "{{ mnt_path }}"
        state: directory
        mode: "0777"

    - name: Mount nvme
      become: true
      ansible.posix.mount:
        path: "{{ mnt_path }}"
        src: "{{ ssd_device }}"
        fstype: ext4
        state: mounted

    - name: Clear nvme temp directory
      ansible.builtin.file:
        path: "{{ mnt_path }}/tmp"
        state: "{{ item }}"
        mode: "0777"
      loop:
        - absent
        - directory

    - name: Sync workdir
      ansible.posix.synchronize:
        src: "{{ workdir }}/"
        dest: "{{ workdir }}"
        delete: true
        rsync_opts:
          - --exclude=.git
          - --exclude=data

    - name: Install Python dependencies
      ansible.builtin.shell: |
        {{ pythondir }}/pip install -Ur {{ workdir }}/requirements/worker.txt
      changed_when: true

    - name: Install project packages
      ansible.builtin.shell: |
        cd {{ workdir }} && {{ pythondir }}/pip install -e .
        cd {{ workdir }}/raysort/sortlib && {{ pythondir }}/python setup.py build_ext --inplace
      changed_when: true

    - name: Set soft and hard ulimit
      become: true
      community.general.pam_limits:
        domain: "*"
        limit_type: "{{ item }}"
        limit_item: nofile
        value: 65535
      loop:
        - hard
        - soft

    - name: Start Node Exporter
      ansible.builtin.shell: >
        nohup
        {{ workdir }}/raysort/bin/node_exporter/node_exporter
        --web.listen-address 0.0.0.0:8091 &
      changed_when: true
