global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: cluster
    file_sd_configs:
      - files:
        - /tmp/prometheus/service_discovery.json
