{
 "title": "Ray AWS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.5, 1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5s]))",
     "legendFormat": "median cpu"
    },
    {
     "expr": "min(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5s]))",
     "legendFormat": "min cpu"
    },
    {
     "expr": "max(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5s]))",
     "legendFormat": "max cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "quantile(0.5, ray_object_store_used_memory)",
     "legendFormat": "median objmem"
    },
    {
     "expr": "min(ray_object_store_used_memory)",
     "legendFormat": "min objmem"
    },
    {
     "expr": "max(ray_object_store_used_memory)",
     "legendFormat": "max objmem"
    },
    {
     "expr": "quantile(0.5, ray_node_mem_used)",
     "legendFormat": "median workmem"
    },
    { "expr": "min(ray_node_mem_used)", "legendFormat": "min workmem" },
    { "expr": "max(ray_node_mem_used)", "legendFormat": "max workmem" }
   ]
  },
  {
   "title": "Application Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "ray_map_in_progress", "legendFormat": "map_in_progress" },
    { "expr": "ray_reduce_in_progress", "legendFormat": "reduce_in_progress" },
    { "expr": "ray_map_completed", "legendFormat": "map_completed" },
    { "expr": "ray_reduce_completed", "legendFormat": "reducer_completed" },
    { "expr": "ray_merge_in_progress", "legendFormat": "merge_in_progress" },
    { "expr": "ray_merge_completed", "legendFormat": "merge_completed" }
   ]
  },
  {
   "title": "NVMe Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile(0.5, sum by (instance) (irate(node_disk_written_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "median disk write"
    },
    {
     "expr": "min(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "min disk write"
    },
    {
     "expr": "max(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "max disk write"
    },
    {
     "expr": "quantile(0.5, sum by (instance) (irate(node_disk_read_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "median disk read"
    },
    {
     "expr": "min(sum by (instance) (irate(node_disk_read_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "min disk read"
    },
    {
     "expr": "max(sum by (instance) (irate(node_disk_read_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "max disk read"
    },
    {
     "expr": "quantile(0.5, sum by (instance) (irate(node_disk_written_bytes_total{device=~\"nvme.+\"}[5s]) + irate(node_disk_read_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "median disk total"
    },
    {
     "expr": "max(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"nvme.+\"}[5s]) + irate(node_disk_read_bytes_total{device=~\"nvme.+\"}[5s])))",
     "legendFormat": "max disk total"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile(0.5, irate(node_network_receive_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "median network in"
    },
    {
     "expr": "min(irate(node_network_receive_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "min network in"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "max network in"
    },
    {
     "expr": "quantile(0.5, irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "median network out"
    },
    {
     "expr": "min(irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "min network out"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "max network out"
    },
    {
     "expr": "quantile(0.5, irate(node_network_receive_bytes_total{device=~\"ens.+\"}[5s]) + irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "median network total"
    },
    {
     "expr": "min(irate(node_network_receive_bytes_total{device=~\"ens.+\"}[5s]) + irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "min network total"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]) + irate(node_network_transmit_bytes_total{device=~\"ens.+\"}[5s]))",
     "legendFormat": "max network total"
    }
   ]
  },
  {
   "title": "Time",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ray_mapper_time_bucket", "legendFormat": "{{le}}" },
    { "expr": "ray_reducer_time_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Ray Object Bytes Pending Spill",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(ray_spill_manager_objects_bytes{State=\"PendingSpill\"})",
     "legendFormat": "avg disk write"
    },
    {
     "expr": "min(ray_spill_manager_objects_bytes{State=\"PendingSpill\"})",
     "legendFormat": "min disk write"
    },
    {
     "expr": "max(ray_spill_manager_objects_bytes{State=\"PendingSpill\"})",
     "legendFormat": "max disk write"
    }
   ]
  },
  {
   "title": "EBS I/O",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "avg disk write"
    },
    {
     "expr": "min(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "min disk write"
    },
    {
     "expr": "max(sum by (instance) (irate(node_disk_written_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "max disk write"
    },
    {
     "expr": "avg(sum by (instance) (irate(node_disk_read_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "avg disk read"
    },
    {
     "expr": "min(sum by (instance) (irate(node_disk_read_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "min disk read"
    },
    {
     "expr": "max(sum by (instance) (irate(node_disk_read_bytes_total{device=~\"xvdb.+\"}[5s])))",
     "legendFormat": "max disk read"
    }
   ]
  }
 ]
}