---
- hosts: all
  vars:
    head_ip: 172.31.27.175
    mnt_path: /mnt/nvme0
    workdir: ~/raysort
    pythondir: ~/miniconda3/envs/raysort/bin
  tasks:
    - name: Clear nvme temp directory
      become: yes
      file:
        path: "{{mnt_path}}/tmp"
        state: absent

    - name: Create nvme temp directory
      become: yes
      file:
        path: "{{mnt_path}}/tmp"
        state: directory
        mode: "777"

    - name: Stop Ray
      shell: "{{pythondir}}/ray stop -f"
      args:
        executable: /bin/bash

    - name: Start Ray
      shell: >
        nohup
        {{pythondir}}/ray start
        --address={{head_ip}}:6379
        --object-manager-port=8076
        --metrics-export-port=8090
        --resources='{"worker":1}'
        --object-store-memory={{28 * 1024 * 1024 * 1024}}

    - name: Start Node Exporter
      shell: >
        nohup
        {{workdir}}/raysort/bin/node_exporter/node_exporter
        --web.listen-address 0.0.0.0:8091 &
