name: Single Node Sort Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      RAY_memory_usage_threshold: 1.0
      S3_BUCKET: raysort-github-ci
      TMPFS_PATH: /mnt/tmpfs/raysort
      WANDB_MODE: offline
    steps:
      - name: Mount tmpfs
        run: |
          sudo mkdir /mnt/tmpfs
          sudo mount -t tmpfs tmpfs /mnt/tmpfs

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/worker.txt

      - name: Install project package
        run: |
          pip install -e .
          pushd raysort/sortlib && python setup.py build_ext --inplace && popd

      - name: Install gensort binary dependencies
        run: scripts/installers/install_binaries.sh gensort

      - name: 1GB simple shuffle
        env:
          CONFIG: LocalSimple
        run: python raysort/main.py

      - name: 1GB two stage shuffle with manual spilling
        env:
          CONFIG: LocalManualSpillingDisk
        run: python raysort/main.py

      - name: 1GB two stage shuffle with manual spilling, parallelized
        env:
          CONFIG: LocalManualSpillingDiskParallel
        run: python raysort/main.py

      - name: 1GB Ray native shuffle
        env:
          CONFIG: LocalNative
        run: python raysort/main.py

      - name: 1GB Ray native shuffle with ray.put()
        env:
          CONFIG: LocalNativePut
        run: python raysort/main.py

      - name: 1GB Ray native shuffle with generator tasks
        env:
          CONFIG: LocalNativeYield
        run: python raysort/main.py

      # Disabled due to OOM on GitHub CI
      # - name: 1GB Ray native shuffle, reduce only
      #   env:
      #     CONFIG: LocalNativeReduceOnly
      #   run: python raysort/main.py

      - name: 1GB Ray native shuffle, Magnet version
        env:
          CONFIG: LocalMagnet
        run: python raysort/main.py

      - name: 1GB Ray native shuffle, Riffle version
        env:
          CONFIG: LocalRiffle
        run: python raysort/main.py

      - name: 1GB Ray native shuffle on skewed data
        env:
          CONFIG: LocalSkew
        run: python raysort/main.py
