name: Single Node End-to-End Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WANDB_MODE: offline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/worker.txt

      - name: Install project package
        run: |
          pip install -e .
          pushd raysort/sortlib && python setup.py build_ext --inplace && popd

      - name: Install gensort binary dependencies
        run: |
          scripts/install_binaries.sh gensort

      - name: 1GB simple shuffle
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --simple_shuffle --ray_address=

      - name: 1GB two stage shuffle with manual spilling
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --manual_spilling --ray_address=

      - name: 1GB Ray native shuffle
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --ray_address=

      - name: 1GB Ray native shuffle with ray.put()
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --use_put --ray_address=

      - name: 1GB Ray native shuffle, Magnet version
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --magnet --ray_address=

      - name: 1GB Ray native shuffle, Riffle version
        run: python raysort/main.py --total_gb=1.28 --input_part_size=10_000_000 --riffle --ray_address=
