name: Single Node Sort Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WANDB_MODE: offline
    steps:
      - name: Mount tmpfs
        run: |
          sudo mkdir /mnt/tmpfs
          sudo mount -t tmpfs tmpfs /mnt/tmpfs

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/worker.txt

      - name: Install project package
        run: |
          pip install -e .
          pushd raysort/sortlib && python setup.py build_ext --inplace && popd

      - name: Install gensort binary dependencies
        run: scripts/installers/install_binaries.sh gensort

      - name: 1GB simple shuffle
        run: CONFIG=LocalSimple python raysort/main.py

      - name: 1GB two stage shuffle with manual spilling
        run: CONFIG=LocalManualSpillingDisk python raysort/main.py

      - name: 1GB two stage shuffle with manual spilling, parallelized
        run: CONFIG=LocalManualSpillingDiskParallel python raysort/main.py

      - name: 1GB Ray native shuffle
        run: CONFIG=LocalNative python raysort/main.py

      - name: 1GB Ray native shuffle with ray.put()
        run: CONFIG=LocalNativePut python raysort/main.py

      - name: 1GB Ray native shuffle, Magnet version
        run: CONFIG=LocalMagnet python raysort/main.py

      - name: 1GB Ray native shuffle, Riffle version
        run: CONFIG=LocalRiffle python raysort/main.py
