name: Single Node Fault Tolerance Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      RAY_memory_usage_threshold_fraction: 1.0
      S3_BUCKET: raysort-github-ci
      STEPS: sort
      WANDB_MODE: offline
    steps:
      - name: Mount tmpfs
        run: |
          sudo mkdir /mnt/tmpfs
          sudo mount -t tmpfs tmpfs /mnt/tmpfs

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/worker.txt

      - name: Install project package
        run: |
          pip install -e .
          pushd raysort/sortlib && python setup.py build_ext --inplace && popd

      - name: 1GB simple shuffle
        env:
          CONFIG: LocalSimpleFT
        run: python raysort/main.py

      - name: 1GB Ray native shuffle
        env:
          CONFIG: LocalNativeFT
        run: python raysort/main.py

      - name: 1GB Ray native shuffle with ray.put()
        env:
          CONFIG: LocalNativePutFT
        run: python raysort/main.py

      - name: 1GB Ray native shuffle, Magnet version
        env:
          CONFIG: LocalMagnetFT
        run: python raysort/main.py

      - name: 1GB Ray native shuffle, Riffle version
        env:
          CONFIG: LocalRiffleFT
        run: python raysort/main.py
